# Importación de datos

```{r, eval=FALSE}
pacman::p_load(tidyverse, googlesheets4, googledrive)
gs4_auth(email = "edwardsmolina@gmail.com")
googledrive::drive_auth(email = "edwardsmolina@gmail.com")
nova_tr <- gs4_get(gs4_find("NOVA_trigo_2020")$id)
# nova_tr %>% sheet_names()
# gs4_browse(nova_tr)
```


```{r, eval=TRUE}
pacman::p_load(tidyverse)
source(here::here('theme_juan.R'))
load("data/nova_trigo.Rdata")
```

## Sanidad 

Interesante que es un dataset con 2 filas de encabezados

```{r eval=FALSE}
data_head <- read_sheet(nova_tr, sheet="full", n_max = 2) 

new_names <- data_head %>%
  t() %>% 
  as_tibble() %>% 
  unite(., col = "name",  V1, V2, na.rm=TRUE, sep = "_") %>% 
  pull(name)
```


```{r, eval=FALSE}
dat_full <- read_sheet(nova_tr, sheet="full", skip = 3, col_names = new_names) 

dat <- dat_full %>%  
  filter(!trt == 16)%>% 
  mutate(fecha = lubridate::ymd(fecha))%>% 
  drop_na(fecha) %>% 
  # mutate(dias = factor(dias)) %>% 
  # mutate(af_sana= verdor-e_int) %>% 
  dplyr::select(id:verdor, matches("e2"), -contains("ABC")) %>% 
  select(-matches("sev")) %>% 
  mutate(af_sana = verdor - int_e2)

# dat %>% view
```

## Cosecha

```{r,  eval=F}
cosecha <- read_sheet(nova_tr, sheet="cosecha") %>% 
  mutate_at(vars(trt,bk), as.factor)  
cosecha
```

* Mapa de parcelas

```{r}
heat1 <- ggplot()+
  geom_point(aes(x = 1:16, y = rep(4.5,16)), size=0.1) +
  scale_x_continuous(breaks=scales::pretty_breaks(n = 16)) +
  scale_y_continuous(breaks=scales::pretty_breaks(n = 4)) +
  cowplot::theme_minimal_grid()+
  # geom_hline(yintercept = 4.5)+
  geom_hline(yintercept = 2.5, linetype = "dashed")+
  geom_segment(aes(x=8.5, y=0.5, xend=8.5, yend=4.5), linetype = "dashed", size =0.3) +
  # geom_segment(aes(x=4.5, y=4.5, xend=4.5, yend=4.5), linetype = "dashed", size =0.3) +
  # geom_segment(aes(x=8.5, y=4.5, xend=8.5, yend=7.5), linetype = "dashed", size =0.3) +
  # geom_segment(aes(x=12.5, y=4.5, xend=12.5, yend=7.5), linetype = "dashed", size =0.3)+
  viridis::scale_fill_viridis(discrete=FALSE, direction = -1)+
  labs(x="col", 
       y="fila", 
       fill = "Rendimiento\n(kg/ha)" )

heat1 + 
  geom_tile(data = cosecha, aes(col, fila, fill= kg_ha), alpha =0.9) +
  geom_text(data = cosecha, 
            aes(x = col, fila,
            label = paste(trt, "\n", round(plot,1), "")), 
            col = "white", size = 3) 

# ggsave(last_plot(), file = "plots/mapa_parcelas.png", w=6.5, h=7)

```


```{r, eval=FALSE}
# dat %>% write_sheet(ss=nova_ceb, sheet = "clean")
save(dat, cosecha, file = "data/nova_trigo.Rdata")
```
