---
title: "Untitled"
output: html_document
date: '2022-07-19'
---
# setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, googlesheets4, metafor, janitor)
conflicted::conflict_prefer("filter", "dplyr")
conflicted::conflict_prefer("select", "dplyr")
load(here::here("red_data/meta_data.Rdata"))
```

```{r cars}
# yield_dat <- yield_dat %>% 
#   mutate(yi = round(log(yield),3), # log of disease yield
#          vi = round(MSE / (bk * yield^2),5), #Sampling variance for yi
#          D = yield - yd_check, # difference (D) in yield: trt - check
#          vi2 = MSE/bk # multivariate approach for Sampling variance of D
#   )
```

# data 
```{r cars}
dat_mean <- dat %>% 
  group_by(id_ensayo, trt) %>% 
  summarise(
    n=sum(!is.na(kg_ha)),
    mean_kg_ha = mean(kg_ha, na.rm=TRUE),
    yi = log(mean_kg_ha))
dat_mean

dat_qm <- dat %>%  
  select(id_ensayo, trt, bk, kg_ha) %>% 
  group_by(id_ensayo) %>% 
  do(broom::tidy(aov(.$kg_ha ~ .$trt + factor(.$bk)))) %>% 
  filter(term == "Residuals") %>% 
  select(1,5) %>% 
  set_names(c("id_ensayo", "v_yld"))
dat_qm

dat_meta <- dat_mean %>% 
  left_join(dat_qm) %>% 
  left_join(info_red) %>% 
  # filter(!id_ensayo=="2019_BARROW") %>% 
  mutate(vi_yld = v_yld/n,
         vi_yi = v_yld/(n * mean_kg_ha^2)) %>% 
  ungroup() %>% 
  mutate(dis_press = fct_relevel(dis_press, c("SIN", "MA", "RY")), 
         ry= factor(ry))

dat_meta
# levels(dat_meta$dis_press)
# sum(is.na(dat_meta))
# dat_meta %>% tabyl(dis_press)
```

# D 
```{r cars}
dat_meta %>% 
  select(id_ensayo, trt, n, dis_press, mean_kg_ha, vi_yld) 

mv_yld <- rma.mv(mean_kg_ha, vi_yld,
                 mods = ~ trt,
                 random = list(~trt|id_ensayo),
                 struct = "UN",
                 method = "ML",
                 control = list(optimizer = "nlm"),
                 data = dat_meta)
summary(mv_yld)
```

# log(yield)

## ry=0

```{r}
mv_logy <- rma.mv(
  yi, vi_yi, 
  mods = ~ trt * ry, 
  random = list(~trt | id_ensayo),
  struct = "UN",
  method = "ML",
  control = list(optimizer = "nlm"),
  data = dat_meta)
```

```{r cars}
summary(mv_logy)
anova(mv_logy, btt = 8:12)
```

## ry=1

```{r cars}
# dat_meta %>% 
#   select(id_ensayo, trt, n, dis_press, yi, vi_yi) 
mv_logy1 <- rma.mv(
  yi, vi_yi, 
  mods = ~ trt * ry, 
  random = list(~trt | id_ensayo),
  struct = "UN",
  method = "ML",
  control = list(optimizer = "nlm"),
  data = dat_meta %>% mutate(ry = fct_relevel(ry, "1")))
```

```{r cars}
summary(mv_logy1)
anova(mv_logy1, btt = 8:12)
```

## res table
```{r}
myfxn <- function(x){
      round((exp(as.numeric(as.character(x)))-1)*100, 2)
    }
```

```{r}
res <-
  with(mv_logy,
       data.frame(
         
         ry_level = rep(c("Ry=0", "Ry=1"), e=5),
         
         trt = gsub("trt","", row.names(mv_logy$b)[c(2:6,8:12)]),         
         pred = c(b[2:6], (b[2:6] + b[8:12])),
         
         lower = c(ci.lb[2:6], (ci.lb[2:6] + ci.lb[8:12])),
         
         upper = c(ci.ub[2:6], (ci.ub[2:6] + ci.ub[8:12]))
       ))
res
```

```{r}
res[,3:5] = lapply(res[3:5],myfxn)
knitr::kable(res)
res %>%  write_sheet(ss=sheet_red, 
                                   sheet = "res_meta")

```



```{r}
anova(mv_logy, L = rbind(
  c(0, -1, 0, 0, 0, 1, 
    0, 0, 0, 0, 0, 0),  
  c(0, 0, -1, 0, 0,1, 
    0, 0, 0, 0, 0, 0),
  c(0, 0, 0, -1, 0, 1, 
    0, 0, 0, 0, 0, 0),  
  c(0, 0, 0, 0, -1, 1, 
    0, 0, 0, 0, 0, 0)
  ))
```


```{r}
anova(mv_logy, L = rbind(
  c(
    0, 0, 0, 0, 0, 0,
    0, -1, 0, 0, 0, 1 
    ),  
  c(
    0, 0, 0, 0, 0, 0,
    0, 0, -1, 0, 0,1 
    ),
  c(
    0, 0, 0, 0, 0, 0, 
    0, 0, 0, -1, 0, 1 
    ),  
  c(
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, -1, 1 
    )
  ))
```

# final plot

```{r}
res %>%   
  mutate(
  trt = str_replace_all(trt, ":ry1", ""),
  trt = fct_relevel(trt, orden_trt[-1])
  ) %>%
  # ry = factor(ry), 
  # ry_level = fct_recode(ry_level, "Predominancia de manchas" = "r0", "Predominancia de royas" = "r1")) %>% 
  ggplot() + 
  aes(x=trt, y=pred) + 
  geom_errorbar(aes(ymin = lower, ymax = upper), alpha = 0.5, width=0, size= 0.8)+
  # geom_errorbarh(aes(xmin = efficacy_lw, xmax = efficacy_up, color = fungicide), alpha = 0.8, height= 0, size= 0.8)+
  geom_point(size = 3, alpha = 0.5)+
  facet_grid(. ~ry_level, scales = "free") +
  geom_text(aes(label = paste0(round(pred,2), "%")), color = "black", size = 3, angle=0, vjust=-0.5)  +
  coord_flip() +
  theme_dens1 + 
  labs(y="Respuesta en rendimiento (%)", x="")
```


```{r}
ggsave(last_plot(), file=here::here("red_plots/res.png"), 
       w = 6, h = 4)
```



```{r cars}
# calcular test con ry 0
# 5752.9323
test.r0 <- data.frame(predict(mv_yld_dis, addx=F, 
                              newmods = c(0,0,0,0,0,
                                          0,
                                          0,0,0,0,0)))
# 5752.9323 + 397.8728
rub_Z32.r0 <- data.frame(predict(mv_yld_dis, addx=F, 
                                 newmods = c(1,0,0,0,0,
                                             0,
                                             0,0,0,0,0)))

orq_Z32.r0 <- data.frame(predict(mv_yld_dis, addx=F, 
                                 newmods = c(0,1,0,0,0,
                                             0,
                                             0,0,0,0,0)))

rub_Z39.r0 <- data.frame(predict(mv_yld_dis, addx=F, 
                                 newmods = c(0,0,1,0,0,
                                             0,
                                             0,0,0,0,0)))

orq_Z39.r0 <- data.frame(predict(mv_yld_dis, addx=F, 
                                 newmods = c(0,0,0,1,0,
                                             0,
                                             0,0,0,0,0)))

rub_Z32_orq_Z39.r0 <- data.frame(predict(mv_yld_dis, addx=F, 
                                         newmods = c(0,0,0,0,1,
                                                     0,
                                                     0,0,0,0,0)))
# calcular test con ry 1 
test.r1<- data.frame(predict(mv_yld_dis, addx=F, 
                             newmods = c(0,0,0,0,0,
                                         1,
                                         0,0,0,0,0)))
rub_Z32.r1 <- data.frame(predict(mv_yld_dis, addx=F, 
                                 newmods = c(1,0,0,0,0,
                                             1,
                                             1,0,0,0,0)))
orq_Z32.r1 <- data.frame(predict(mv_yld_dis, addx=F, 
                                 newmods = c(0,1,0,0,0,
                                             1,
                                             0,1,0,0,0)))
rub_Z39.r1 <- data.frame(predict(mv_yld_dis, addx=F, 
                                 newmods = c(0,0,1,0,0,
                                             1,
                                             0,0,1,0,0)))
orq_Z39.r1 <- data.frame(predict(mv_yld_dis, addx=F, 
                                 newmods = c(0,0,0,1,0,
                                             1,
                                             0,0,1,1,0)))
rub_Z32_orq_Z39.r1 <- data.frame(predict(mv_yld_dis, addx=F, 
                                         newmods = c(0,0,0,0,1,
                                                     1,
                                                     0,0,0,0,1)))
```


```{r cars}
res <- bind_rows(
  lst(test.r0, rub_Z32.r0, orq_Z32.r0, rub_Z39.r0, orq_Z39.r0, 
      rub_Z32_orq_Z39.r0,
      test.r1, rub_Z32.r1, orq_Z32.r1, rub_Z39.r1, 
      orq_Z39.r1, rub_Z32_orq_Z39.r1),  .id = "id" ) %>% 
  separate(id, c("trt", "ry"),  sep="\\.", convert = TRUE, extra = "merge")

res %>% 
  select(ry, trt, pred:ci.ub) %>% 
  write_sheet(ss=sheet_red, sheet = "res_meta")
```


```{r cars}
orden_trt <- c("test", "rub_Z32", "orq_Z32", "rub_Z39", "orq_Z39", "rub_Z32_orq_Z39")

res %>%   
  mutate(trt = fct_relevel(trt, orden_trt), 
         ry = factor(ry), 
         ry = fct_recode(ry, "Predominancia de manchas" = "r0", 
                         "Predominancia de royas" = "r1")) %>% 
  ggplot() + 
  aes(x=trt, y=pred) + 
  geom_errorbar(aes(ymin = ci.lb, ymax = ci.ub), alpha = 0.8, width=0, size= 0.8)+
  # geom_errorbarh(aes(xmin = efficacy_lw, xmax = efficacy_up, color = fungicide), alpha = 0.8, height= 0, size= 0.8)+
  geom_point(size = 3)+
  facet_wrap("ry") +
  geom_text(aes(label = round(pred)), color = "black", size = 3, angle=0, vjust=-0.5)  +
  coord_flip() +
  theme_dens1 + 
   labs(y="Rinde modelado (kg/ha)", 
        x="") 

ggsave(last_plot(), file="red_plots/trigo_red_yield_meta.png",w=4, h=3, scale=1.5)
```
