---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, eval=FALSE}
red_full <- gs4_get(gs4_find("red_trigo_data")$id)
gs4_browse(red_full)
raw <- red_full %>% read_sheet(sheet = "full", guess_max = 10000, skip=0) 
raw %>% count(id_ensayo)
source(here::here("themes.R"))
# raw %>%filter(id_ensayo == "2020_INTA_BCE")
```


```{r message=FALSE, warning=FALSE, eval=FALSE}
info <- red_full %>% read_sheet(sheet = "info") 
info

dat <- raw %>% 
  mutate_if(is.character, as.factor) %>% 
  filter(trt %in% c("test", "rub_Z32", "rub_Z39", "orq_Z32", "orq_Z39", "rub_Z32_orq_Z39")) %>% 
  left_join(info, by="id_ensayo")

dat %>% 
  group_by(id_ensayo, trt) %>% 
  summarise(kg_ha = mean(kg_ha, na.rm = T)) %>% 
  # ungroup() %>% 
  filter(trt %in% c("test", "rub_Z32_orq_Z39")) %>% 
  pivot_wider(names_from = trt, values_from = kg_ha) %>% 
  rename(rinde_doble = rub_Z32_orq_Z39,
         rinde_test = test)->sum
# sum %>%filter(id_ensayo == "2020_INTA_BCE")

dat %>% 
  group_by(id_ensayo, trt) %>% 
  summarise(kg_ha = mean(kg_ha, na.rm = T)) %>%  
  left_join(sum, by = "id_ensayo") %>% 
  rowwise() %>% 
  mutate(dif_test = kg_ha -rinde_test, 
         dif_doble = rinde_doble - kg_ha) %>%
  left_join(info, by = "id_ensayo") ->dat_mean
# dat_mean %>%filter(id_ensayo == "2020_INTA_BCE")

# load(here::here("data/data.Rdata"))
```


```{r}
# dat %>% 
#   ggplot()+
#   aes(trt, kg_ha)+
#   geom_point()+
#   stat_summary(fun.data = "mean_cl_boot", colour = "red", size = 0.5)+
#   facet_wrap("ensayo", scales = "free_y")+
#   stat_summary(aes(label=round(..y..,0)), 
#                fun=mean, geom="text", size=4, vjust = -0.5)+ 
#   coord_flip()+  theme_dens1# +
```


```{r}
roles <- function(x) sub("[^_]*_","",x )# used to create x-axis label restoring original name of role
dat_mean %>% #count(id_ensayo)
  filter(!trt %in% c("test")) %>% 
  mutate(V4=paste(trt, id_ensayo, sep="_")) %>%
  ggplot(aes(x=reorder(V4, dif_test), y=dif_test) ) + 
  geom_bar(aes(fill = enfermedad_1),stat = "identity") +
  # geom_errorbar(width=0.2, size= 0.3, 
  #               aes(ymax = D + sqrt(vi2/sqrt(bk)), 
  #                   ymin=D - sqrt(vi2/sqrt(bk))))+
  facet_wrap(~ trt,  ncol=2, scales = "free_x") +
  scale_x_discrete(labels=roles)+
  labs(y="Dif. test (kg/ha)", x = "Ensayo (ordenado por dif_test) ")+
  theme_bw2+ theme(axis.text.x=element_blank() )+
  geom_abline(intercept = 0)

```


```{r}
dat %>% #count(id_ensayo)
  mutate(trt = fct_relevel(trt, c("test", "rub_Z32", "rub_Z39", "orq_Z32", "orq_Z39", "rub_Z32_orq_Z39"))) %>% 
  filter(id_ensayo == "2020_PABLO_ACOSTA") %>% 
  ggplot()+
  aes(x=trt, y=kg_ha)+
  geom_point(alpha=0.3)+
  # facet_wrap("id_ensayo")+
  stat_summary(fun.data = "mean_cl_boot", colour = "red", size = 0.5)+
  # geom_text(aes)
  stat_summary(data = dat_mean %>% 
                   filter(id_ensayo == "2020_PABLO_ACOSTA"), 
               aes(x=trt, y=kg_ha,
                   label=dif_test %>% round), 
               fun=mean, geom="text", size=4,vjust = -0.5)+
  scale_y_continuous(breaks= scales::pretty_breaks())+
  coord_flip()+
  theme_bw(base_size = 14)
```




```{r}
roles <- function(x) sub("[^_]*_","",x )
n_fun <- function(x){return(data.frame(y = -Inf, label = paste0("n = ",length(x))))}

dat_mean %>% 
  filter(!trt %in% c("test", "rub_Z32_orq_Z39")) %>% 
  mutate(id=paste(trt, id_ensayo, sep="_")) %>% 
  ggplot(aes(x=reorder(id, dif_doble), y=dif_doble) ) + 
  geom_bar(
    # aes(fill = enfermedad_1),
           stat = "identity") +
  # geom_errorbar(width=0.2, size= 0.3, 
  #               aes(ymax = D + sqrt(vi2/sqrt(bk)), 
  #                   ymin=D - sqrt(vi2/sqrt(bk))))+
  facet_grid(enfermedad_1~ trt, scales = "free_x") +
  scale_x_discrete(labels=roles)+
  labs(y="Dif. test (kg/ha)", x = "Ensayo (ordenado por dif_test) ")+
  theme_bw2 + 
  theme(axis.text.x=element_blank())+
  geom_abline(intercept = 200)+
  geom_abline(intercept = 0)+
  geom_text(aes(x= id, y=dif_doble, label = dif_doble %>% round(), 
                fill = NA), angle = 0, size =2)
  # geom_text(aes(x= id, y=0, label = id_ensayo, fill = NA), angle = 90, size =2) 

```

```{r}
df %>% 
  ggplot()+
  aes(trt, kg_ha)+
  geom_point()+
  stat_summary(fun.data = "mean_cl_boot", colour = "red", size = 0.5)+
  facet_grid(. ~ ensayo, scales = "free_y")+
  stat_summary(aes(label=round(..y..,0)), 
               fun=mean, geom="text", size=4, vjust = -0.5)+ 
  coord_flip()+
  theme_dens1# +
  # stat_summary(fun.data = n_fun, geom = "text", vjust = -0.5)+
```